import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar from './components/navbar/NavBar'
import AuthProvider from './auth/provider'
import Link from 'next/link'

// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="luxury">
      <body className='bg-orange-200'>
        <AuthProvider>
          <nav>
              <NavBar />
          </nav>
          <main className='hero'>{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
